Updated translations
City-of-Helsinki/open-city-profile-ui pull request #221
Opened 2021-11-18 12:46 UTC by NikoHelle

Latest version of all translations. No untranslated keys.

2021-11-19 11:09 UTC, akikoskinen requested changes

2021-11-19 11:09 UTC, akikoskinen commented on src/i18n/sv.json
> +    "description": "Helsinki-profilen gör det möjligt att använda dina uppgifter i alla Helsingfors webbtjänster som kräver identifiering. Samma information, enkel att använda i många olika tjänster.
From the Swedish translation file I can find:

- Helsingfors-profil
- Helsinki-profil
- Helsingfors profil

Would probably be good to stick to only one term.

2021-11-19 11:09 UTC, akikoskinen commented on src/i18n/sv.json
> +  "pageNotFoundText": "Kontrollera att URL-adressen är rätt skriven (kontrollera stora och små bokstäver och skiljetecken). Eller gå tillbaka till föregående sida genom att klicka på tangenten Föregå
There's a closing parenthesis where there should be a full stop (after the word "webbläsaren").

2021-11-22 10:23 UTC, NikoHelle commented on src/i18n/sv.json
> +    "description": "Helsinki-profilen gör det möjligt att använda dina uppgifter i alla Helsingfors webbtjänster som kräver identifiering. Samma information, enkel att använda i många olika tjänster.
Good catch! 👍 "Helsingfors-profil" was chosen.

2021-11-22 10:23 UTC, NikoHelle commented on src/i18n/sv.json
> +  "pageNotFoundText": "Kontrollera att URL-adressen är rätt skriven (kontrollera stora och små bokstäver och skiljetecken). Eller gå tillbaka till föregående sida genom att klicka på tangenten Föregå
Fixed!

2021-11-23 09:00 UTC, akikoskinen approved these changes

2021-11-24 07:12 UTC, merged