HP-1796: UI facelift
City-of-Helsinki/open-city-profile-ui pull request #287
Opened 2023-03-02 10:10 UTC by NikoHelle

Changed styles according to the [new design](https://share.goabstract.com/ef4b8648-6b86-41b9-b1c2-f0c78721a436?collectionLayerId&mode).

Also cleaned up the codebase. Removed "multi-item"-related components, because those have been obsolete for a while. A lot of code was merged to make components simpler and after that it was easier to make style changes, because container elements were unified and common styles easier to use.

This branch is currently in https://profiili.dev.hel.ninja/

2023-03-06 09:43 UTC, akikoskinen reviewed
Overall looks nice. I see some differences between the implementation and the design. Are these intentional, or should I point them out?

Also this one error view could perhaps use some style tuning:

<img width="871" alt="Screenshot_20230306_113507" src="https://user-images.githubusercontent.com/758558/223073764-160fd029-1103-4872-98a3-79984c98e853.png">

2023-03-07 07:16 UTC, NikoHelle commented
I'll have to make some changes to the buttons. Otherwise implementation should be ok, at least designer did not say anything. The design is based on hel.fi, but we use HDS, so they cannot match 100%.

I'll add padding to the error too.

2023-03-08 06:08 UTC, akikoskinen requested changes
Not sure if this PR is the reason for this behavior, but I noticed the following. Locally I shut down Profile API, so that Profile UI can't save any profile data changes. When I edit some data and try to save, an error message is shown correctly. When I then click the save button again, Profile UI doesn't even try to send the data to Profile API, it just informs that saving was successful.

2023-03-08 06:37 UTC, akikoskinen reviewed
Here's a collection of some error messages. While they all look nice on their own, they all look different. Would it be important to use a unified style for the error messages, or is that not a goal?

<img width="855" alt="Screenshot_20230308_083047" src="https://user-images.githubusercontent.com/758558/223637395-35fe350d-4225-48e2-b92e-f9a311d79b1b.png">
<img width="899" alt="Screenshot_20230308_083108" src="https://user-images.githubusercontent.com/758558/223637404-f0eb91d3-dc95-4473-b381-20c62fac0ff6.png">
<img width="336" alt="Screenshot_20230308_083331" src="https://user-images.githubusercontent.com/758558/223637411-fa758452-06ff-4c52-a41e-fcde23ffa091.png">
<img width="452" alt="Screenshot_20230308_083406" src="https://user-images.githubusercontent.com/758558/223637414-e4de9eec-68f6-4b45-8630-cd499eeb98a8.png">
<img width="564" alt="Screenshot_20230308_083452" src="https://user-images.githubusercontent.com/758558/223637418-0bcbca82-1ba0-4f0b-bd90-2a59f02199ae.png">

2023-03-08 18:48 UTC, NikoHelle commented
Great summary of errors! Thx!

Here are fixed ones

![image](https://user-images.githubusercontent.com/2639230/223796425-82be37ef-f1a9-4ed4-995c-40af0ba672e3.png)

And success messages
![image](https://user-images.githubusercontent.com/2639230/223797258-a42379e8-9b6f-43a6-80f8-5ce27aaca760.png)

2023-03-08 18:58 UTC, NikoHelle commented
> Not sure if this PR is the reason for this behavior, but I noticed the following. Locally I shut down Profile API, so that Profile UI can't save any profile data changes. When I edit some data and try to save, an error message is shown correctly. When I then click the save button again, Profile UI doesn't even try to send the data to Profile API, it just informs that saving was successful.

This is also in the old version, produceable in the test env. But only with emails, where data is not sent, if new email matched the old one. Same feature was added to other fields in this pr. The bug is fixed now and tests were added to prevent it.

2023-03-09 09:49 UTC, akikoskinen requested changes
Only one commit squashing and a typo left to fix.

2023-03-09 09:49 UTC, akikoskinen commented on src/profile/components/phoneNumberEditor/PhoneNumberFormAndData.tsx
> +    noticationContent,
Typo: `noticationContent`.

2023-03-10 10:22 UTC, NikoHelle commented on src/profile/components/phoneNumberEditor/PhoneNumberFormAndData.tsx
> +    noticationContent,
Fixed - also in all files where used

2023-03-10 10:27 UTC, NikoHelle commented
SonarCloud complained again about duplicate code in test files. Ended up re-writing all editing tests.

Gathered all test scenarios to one file and use that is all editing tests. 

Editing tests follow same flow in all tests ,so it was quite convenient to gather them. 

Data and input validation and test initialisations differ, so that took same time to convert to common tests. 

Additions start at in [this commit](https://github.com/City-of-Helsinki/open-city-profile-ui/pull/287/commits/e2bb6b844ba2f9460fe2e65386cc3ad56701641c)

2023-03-10 10:40 UTC, akikoskinen approved these changes
:+1:

2023-03-15 07:13 UTC, merged