[WIIP] HP-2255 replace CRA with Vite
City-of-Helsinki/open-city-profile-ui pull request #314
Opened 2024-02-20 10:08 UTC by mikkojamG

2024-02-26 07:49 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-26 08:47 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-26 09:23 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-26 10:54 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-26 12:13 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-26 12:33 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-27 08:15 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-27 11:14 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-27 12:18 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-27 12:31 UTC, Riippi requested changes

2024-02-27 12:31 UTC, Riippi commented on scripts/update-runtime-env.ts
> +// Prevent collision is app is running while tests are started
is app is  -> if app is ?

2024-02-27 12:37 UTC, mikkojamG commented on scripts/update-runtime-env.ts
> +// Prevent collision is app is running while tests are started
Fixed: https://github.com/City-of-Helsinki/open-city-profile-ui/pull/314/commits/887d9694a491b33d0e4c756d7689a0406c449268

2024-02-27 12:51 UTC, Riippi approved these changes
Great success 👍

2024-02-27 13:01 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-27 13:08 UTC, arpargo commented on scripts/update-translations.ts
En ymmärrä näiden muutosten tarpeellisuutta suoralta kädeltä, voitko avata hieman?

2024-02-27 13:22 UTC, arpargo approved these changes
LGTM

2024-02-28 06:20 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr314-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-28 06:27 UTC, merged