feat: about page HP-2259
City-of-Helsinki/open-city-profile-ui pull request #325
Opened 2024-03-21 08:00 UTC by timwessman

About page in three languages. 

[HP-2259](https://helsinkisolutionoffice.atlassian.net/browse/HP-2259)

2024-03-21 08:17 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr325-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-03-21 11:40 UTC, mikkojamG requested changes

2024-03-21 11:40 UTC, mikkojamG commented on src/common/footer/Footer.tsx
> +        <HDSFooter.Link as={Link} to="/about" label={t('footer.about')} />
According to ticket description, this should be located next to Accessibility document and Cookie settings. 🤔 Moving this inside `<HDSFooter.Base />` should do the trick

2024-03-21 11:40 UTC, mikkojamG commented on src/aboutPage/AboutPage.tsx
> +    const lang =
Could also use `i18n.language` 🤔

2024-03-21 11:40 UTC, mikkojamG commented on src/aboutPage/AboutPageEn.tsx
> +        <ul>
I noticed that there is a console warning: `<ul> cannot appear as a descendant of <p>`. Should be an easy fix 🤔

2024-03-21 11:41 UTC, mikkojamG requested changes

2024-03-21 11:41 UTC, mikkojamG commented on src/aboutPage/AboutPage.tsx
> +function AboutPage(): React.ReactElement {
Looks like Sonar is complaining about test coverage on these about pages. There isn't much to test, could add simple tests just to see that everything renders correctly. 🙂

2024-04-03 08:18 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr325-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-04-03 09:02 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr325-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-04-03 09:38 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr325-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-04-03 12:55 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr325-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-04-03 13:29 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr325-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-04-04 07:08 UTC, mikkojamG approved these changes

2024-04-04 07:25 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr325-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-04-04 07:27 UTC, merged