test: add playwright tests
City-of-Helsinki/open-city-profile-ui pull request #343
Opened 2024-05-07 11:09 UTC by roope-ankka

## What?

This PR adds e2e browser tests implemented with Playwright. These tests are mean to replace the existing TestCafe and Robot Framework tests for Helsinki Profile.

## How to test

Run locally `yarn run test:e2e` and verify that all tests pass

2024-05-07 11:34 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-08 07:05 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-08 08:04 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-08 10:24 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-08 10:56 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-30 10:03 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-30 10:48 UTC, mikkojamG requested changes

2024-05-30 10:48 UTC, mikkojamG commented on e2e/tests/login-methods.spec.ts
> +  const YLE_ACCOUNT_PASSWORD = '1qaz2wsx3edc';
Ideally this should be moved to a env variables, it's not a good pratice to haves username +  passwords visible in code 😬 Also the commit where these are added should be dropped from commit history.

2024-05-30 12:06 UTC, roope-ankka commented on e2e/tests/login-methods.spec.ts
> +  const YLE_ACCOUNT_PASSWORD = '1qaz2wsx3edc';
Whoopsie 😊 YLE test user credentials are now read from environment variables. I changed the password of our "Emeritus Tarmo" just in case 😄

2024-05-30 12:24 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-31 11:34 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr343-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-31 11:57 UTC, mikkojamG approved these changes
LGTM 👍

2024-06-03 11:54 UTC, merged