feat: remove all adresses/phonenumbers when one is removed HP-2338
City-of-Helsinki/open-city-profile-ui pull request #349
Opened 2024-05-16 12:06 UTC by Riippi

Remove all addresses if one is removed. This is to clean up situations where user has multiple addresses (legacy).  
Same for phone numbers. Would also affect email, but it's not possible to remove email from ui.

Before this change if user has multiple addresses removing the address would just change it to the next one in line.

Can be tested by adding multiple addresses and phone numbers in django admin view.

https://helsinkisolutionoffice.atlassian.net/browse/HP-2338

2024-05-16 12:20 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr349-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-20 05:14 UTC, mikkojamG requested changes

2024-05-20 05:14 UTC, mikkojamG commented on src/profile/helpers/editData.ts
> +  const newList = _.cloneDeep(allItems).map(element => ({
Noticed there is a Sonar suggestion that we can return this immediately:
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=349&id=City-of-Helsinki_open-city-profile-ui&open=AY-BUD0YbXIfC8RMhKz7

2024-05-20 06:34 UTC, terovirtanen commented
**HELSINKI-PROFILE-UI branch is deployed to platta: https://helsinki-profile-pr349-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-20 08:08 UTC, mikkojamG approved these changes

2024-05-20 09:52 UTC, merged